<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'anilha',
'quantidade',
'fcbinicio',
'fcbfim',
'mapainicio',
'mapafim',
'socio',
'mapafimbase',
'fcbfimbase',
'clube' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'socio' => array( 'import_field' ),
'anilha' => array( 'import_field1' ),
'quantidade' => array( 'import_field2' ),
'fcbinicio' => array( 'import_field3' ),
'fcbfim' => array( 'import_field4' ),
'mapainicio' => array( 'import_field5' ),
'mapafim' => array( 'import_field6' ),
'mapafimbase' => array( 'import_field7' ),
'fcbfimbase' => array( 'import_field8' ),
'clube' => array( 'import_field9' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field',
'import_field7',
'import_field8',
'import_field9' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field',
'import_field7',
'import_field8',
'import_field9' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'socio',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'anilha',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'quantidade',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'fcbinicio',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'fcbfim',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'mapainicio',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'mapafim',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'mapafimbase',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'fcbfimbase',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'clube',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>