<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_anilha  extends eventsBase
{
	function __construct()
	{
	// fill list of events

		$this->events["AfterAdd"]=true;

		$this->events["AfterDelete"]=true;

		$this->events["BeforeAdd"]=true;

		$this->events["BeforeMoveNextList"]=true;

		$this->events["CustomAdd"]=true;

		$this->events["BeforeShowAdd"]=true;


		$this->events["BeforeProcessList"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, $pageObject)
{

		

// Place event code here.
// Use "Add Action" button to add code snippets.

$i = 0;
$quantidade = (int) $values['quantidade'];


while($i < $quantidade) {

$serie = (int) $values['fcbinicio'] + $i;
$mapa = (int) $values['mapainicio'] + $i;

DB::Query("

INSERT INTO 
anilhas (serie, mapa, status, idanilha)
VALUES ('{$serie}', '{$mapa}', 'ATIVO', {$values['id']}) 

");

echo DB::LastError();


$i++;

}



;		
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record deleted
function AfterDelete($where, &$deleted_values, &$message, $pageObject)
{

		

// Place event code here.
// Use "Add Action" button to add code snippets.

DB::Query("DELETE FROM anilhas WHERE idanilha = '{$deleted_values['id']}' ");

DB::Query("DELETE FROM vanilhas WHERE anilha = '{$deleted_values['id']}' ");
;		
} // function AfterDelete

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record added
function BeforeAdd(&$values, &$message, $inline, $pageObject)
{

		$fcbi = (int) $values['fcbinicio']; 
$fcbf = (int) $values['fcbfim'];

$mi = (int) $values['mapainicio'];
$mf = (int) $values['mapafim'];

$serie = DB::Query("

SELECT 
count(*) as total 
FROM 
anilhas 
WHERE serie BETWEEN {$fcbi} AND {$fcbf} ");

$serie = $serie->fetchAssoc()['total'];

$mapa = DB::Query("

SELECT 
count(*) as total 
FROM 
anilhas 
WHERE mapa BETWEEN {$mi} AND {$mf} ");

$mapa = $mapa->fetchAssoc()['total'];


if($serie > 0) {
	$message = "Esse intervalo de série já foi lançado!";
  return false;
} else if($mapa > 0) {
	$message = "Esse intervalo de mapa já foi lançado!";
  return false;
} else {
	return true;
}


;		
} // function BeforeAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// List page: After record processed
function BeforeMoveNextList(&$data, &$row, &$record, $recordId, $pageObject)
{

		



$disponivel = (int) $data['disponivel'];

if($disponivel == 0) {

$pageObject->hideItem("custom_button", $recordId);

}

// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function BeforeMoveNextList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Custom add
function CustomAdd(&$values, &$keys, &$error, $inline, $pageObject)
{

		

// Place event code here.
// Use "Add Action" button to add code snippets.

$values['disponivel'] = $values['quantidade'];

return true;
;		
} // function CustomAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowAdd(&$xt, &$templatefile, $pageObject)
{

		

// Place event code here.
// Use "Add Action" button to add code snippets.

if($_SESSION['GroupID'] == 'DIRIGENTE') {

$pageObject->setProxyValue('dirigente', true);

}
;		
} // function BeforeShowAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

				// List page: Before process
function BeforeProcessList($pageObject)
{

		

// Place event code here.
// Use "Add Action" button to add code snippets.

//$pageObject->hideItem("custom_button");


;		
} // function BeforeProcessList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
