<?php
$securitySettings_var = array( 'providers' => array( array( 'type' => '%db',
'activationField' => '',
'active' => true,
'code' => '00',
'emailField' => 'email',
'extUserIdField' => null,
'fullnameField' => 'nome',
'label' => array( 'text' => 'Database',
'type' => 0 ),
'name' => 'db',
'passwordField' => 'senha',
'resetDateField' => 'reset_date',
'resetTokenField' => 'reset',
'table' => array( 'connId' => 'columbofilia_at_localhost',
'table' => 'socio' ),
'userGroupField' => 'perfilusu',
'usernameField' => 'email',
'userpicField' => '' ) ),
'sessionControl' => array( 'lifeTime' => 15,
'sessionName' => 'MiHm42OdMmlxZOvNamQe',
'JWTSecret' => 'UGaTpRiM1YybnlhaMhrj' ),
'registration' => array( 'passwordValidation' => array( 'strong' => false,
'minimumLength' => 8,
'uniqueCharacters' => 4,
'digitsAndSymbols' => 2,
'upperAndLowerCase' => false ),
'remindMethod' => 1,
'hashAlgorithm' => 0,
'changePasswordPage' => true,
'changePwdPage' => true,
'registerPage' => false,
'remindPage' => true,
'remindPasswordPage' => true ),
'captchaSettings' => array( 'captchaType' => 0,
'siteKey' => '',
'secretKey' => '',
'passesCount' => 5 ),
'emailSettings' => array( 'fromEmail' => 'web@fcb.org.br',
'usePHPDefinedSMTP' => false,
'useBuiltInMailer' => false,
'SMTPServer' => 'smtp.hostinger.com',
'SMTPPort' => 465,
'SMTPUser' => 'web@fcb.org.br',
'SMTPPassword' => 'cijdiq-0qoxzy-vyjKim',
'securityProtocol' => 1 ),
'advancedSecurity' => array( 'allowGuestLogin' => false,
'tables' => array( 'anilha' => array( 'mainOwnerIDField' => 'id',
'securityOption' => 0,
'userOwnerIDField' => 'id' ),
'anilhas' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'clube' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'cores' => array( 'mainOwnerIDField' => 'usuario',
'securityOption' => 1,
'userOwnerIDField' => 'id' ),
'federacao' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'pedigree' => array( 'mainOwnerIDField' => 'usuario',
'securityOption' => 1,
'userOwnerIDField' => 'id' ),
'pombo' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'socio' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'vanilhas' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ) ) ),
'auditAndLocking' => array( 'loggingTable' => array(  ),
'lockingTable' => array(  ),
'tables' => array(  ),
'loggingMode' => 0,
'loggingFile' => 'audit.log',
'logSecurityActions' => false,
'lockAfterUnsuccessfulLogin' => false,
'enableLocking' => false ),
'twoFactorSettings' => array( 'available' => false,
'required' => false,
'enable' => true,
'remember' => true,
'types' => array(  ),
'twoFactorField' => '',
'emailField' => '',
'phoneField' => '',
'codeField' => '',
'projectName' => '' ),
'projectName' => 'columbofilia',
'loginDataSource' => 'socio',
'loginForm' => 0,
'dynamicPermissions' => false,
'dpTablePrefix' => '',
'dpTableConnId' => '',
'hardcodedLogin' => false,
'enabled' => true,
'advancedSecurityAvailable' => true,
'userGroupsAvailable' => true,
'defaultProviderCode' => '00',
'adOnlyLogin' => false,
'dbProvider' => array( 'type' => '%db',
'activationField' => '',
'active' => true,
'code' => '00',
'emailField' => 'email',
'extUserIdField' => null,
'fullnameField' => 'nome',
'label' => array( 'text' => 'Database',
'type' => 0 ),
'name' => 'db',
'passwordField' => 'senha',
'resetDateField' => 'reset_date',
'resetTokenField' => 'reset',
'table' => array( 'connId' => 'columbofilia_at_localhost',
'table' => 'socio' ),
'userGroupField' => 'perfilusu',
'usernameField' => 'email',
'userpicField' => '' ),
'adAdminGroups' => array(  ),
'showUserSource' => false,
'dbProviderCodes' => array( '00' ),
'notifications' => array(  ) );
?>