<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_vanilhas  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeProcessAdd"]=true;

		$this->events["BeforeProcessEdit"]=true;

		$this->events["CustomAdd"]=true;

		$this->events["CopyOnLoad"]=true;

		$this->events["ProcessValuesAdd"]=true;

		$this->events["AfterAdd"]=true;



		$this->events["AfterDelete"]=true;


	}

//	handlers

		
		
				// Add page: Before process
function BeforeProcessAdd($pageObject)
{

		

// Place event code here.
// Use "Add Action" button to add code snippets.

$pageObject->hideItem('integrated_edit_field6');
$pageObject->hideItem('integrated_edit_field7');
$pageObject->hideItem('integrated_edit_field8');
$pageObject->hideItem('integrated_edit_field9');

;		
} // function BeforeProcessAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
				// Edit page: Before process
function BeforeProcessEdit($pageObject)
{

		

// Place event code here.
// Use "Add Action" button to add code snippets.

$pageObject->hideItem('integrated_edit_field6');
;		
} // function BeforeProcessEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Custom add
function CustomAdd(&$values, &$keys, &$error, $inline, $pageObject)
{

		
$anilha = DB::Query("SELECT * FROM anilha WHERE id = '{$values['anilha']}' ");
$anilha = $anilha->fetchAssoc();

$quantidade = (int) $values['quantidade'];
$disponivel = (int) $anilha['disponivel'];


if( ($quantidade > 0) AND ($quantidade <= $disponivel) ) {

  $serie_inicio = (int) $values['fcbinicio'];
  $mapa_inicio = (int) $values['mapainicio'];
  $serie_fim = $serie_inicio + $quantidade - 1;
  $mapa_fim = $mapa_inicio + $quantidade - 1;


   
 $query = "
        UPDATE anilhas
        SET socio = '{$values['socio']}'
        WHERE CAST(serie AS UNSIGNED) BETWEEN {$serie_inicio} AND {$serie_fim}
        AND CAST(mapa AS UNSIGNED) BETWEEN {$mapa_inicio} AND {$mapa_fim}
    ";

	DB::Query($query);


$disponivel = (int) $anilha['disponivel'] - $values['quantidade'];

DB::Query("UPDATE anilha SET disponivel = '{$disponivel}' WHERE id = '{$anilha['id']}' ");

return true;


}
;		
} // function CustomAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
				// Copy page: OnLoad
function CopyOnLoad(&$values, &$where, $pageObject)
{

		


// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function CopyOnLoad

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Process record values
function ProcessValuesAdd(&$values, $pageObject)
{

		

if(isset($_GET['anilha'])) {

$anilha = DB::Query("SELECT * FROM anilha WHERE id = '{$_GET['anilha']}' ");
$anilha = $anilha->fetchAssoc();

$values['anilha'] = $anilha['id'];

$values['fcbinicio'] = $anilha['fcbfim'] - $anilha['disponivel'] + 1;
$values['fcbfimbase'] = $anilha['fcbfim'];


$values['mapainicio'] = $anilha['mapafim'] - $anilha['disponivel'] + 1;
$values['mapafimbase'] = $anilha['mapafim'];

$values['clube'] = $anilha['clube'];

}
;		
} // function ProcessValuesAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, $pageObject)
{

		

// Place event code here.
// Use "Add Action" button to add code snippets.
$pageObject->setProxyValue('saved', true);
echo "<!doctype html>";

;		
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record deleted
function AfterDelete($where, &$deleted_values, &$message, $pageObject)
{

		
$anilha = DB::Query("SELECT * FROM anilha WHERE id = '{$deleted_values['anilha']}' ");
$anilha = $anilha->fetchAssoc();

$disponivel = (int) $anilha['disponivel'] + $deleted_values['quantidade'];

DB::Query("UPDATE anilha SET disponivel = '{$disponivel}' WHERE id = '{$anilha['id']}' ");


$serie_inicio = (int) $deleted_values['fcbinicio'];
$mapa_inicio = (int) $deleted_values['mapainicio'];
$serie_fim = $serie_inicio + (int)$deleted_values['quantidade'] - 1;
$mapa_fim = $mapa_inicio + (int)$deleted_values['quantidade'] - 1;

DB::Query("
    UPDATE anilhas
    SET socio = NULL
    WHERE CAST(serie AS UNSIGNED) BETWEEN {$serie_inicio} AND {$serie_fim}
    AND CAST(mapa AS UNSIGNED) BETWEEN {$mapa_inicio} AND {$mapa_fim}
");


$pageObject->setProxyValue('delete', true);
;		
} // function AfterDelete

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
